<?php

/**
 * PluginCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCategory');
    }
}