<?php

/**
 * PluginPost
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7294 2010-03-02 17:59:20Z jwage $
 */
abstract class PluginPost extends BasePost
{
  public function getDate($culture = 'en', $complete = true)
  {
    $dt = $this->getDateTimeObject('created_at');
    $day = $dt->format('d');
    $month = $dt->format('F');

    if($culture =='fr')
    {
      $month = PostTable::$fr_month[$month];
    }

    $year = $dt->format('Y');

    $date = $day.' '.$month.' '.$year;

    if($complete)
    {
      $hour = $dt->format('H');
      $minuts = $dt->format('i');
      $date .= ', '.$hour.' h '.$minuts;
    }

    return $date;
  }
}