<?php

/**
 * PluginPostCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPostCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPostCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPostCategory');
    }
}