Post:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    user_id: integer
    title:   string(255)
    username: string(255)
    content: clob(4096)
    is_publish: boolean
  relations:
    Comments:
      type: many
      class: Comment
      local: id
      foreign: post_id
    user:
      class: sfGuardUser
      local: user_id
      foreign: id
      foreignAlias: Posts
  actAs:
    Timestampable: ~
    Sluggable:
      unique: true
      fields: [title]
      canUpdate: true
    
  
    
  

Comment:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    post_id: integer
    user_id: integer
    username: string(255)
    title: string(255)
    content: clob(4096)
  relations:
    User:
      class: sfGuardUser
      local: user_id
      foreign: id
      foreignAlias: comments
    Post:
      class: Post
      local: post_id
      foreign: id
      foreignAlias: comments
  actAs:
    Timestampable: ~
    
Alert:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    post_id: integer
    user_id: integer
    mail:  varchar(255)
    active: boolean
  relations:
    post:
      class: Post
      local: post_id
      foreign: id
    user:
      class: sfGuardUser
      local: user_id
      foreign: id
      foreignAlias: Alerts
      
PostCategory:
  columns:
    id: 
      type: integer
      primary: true
      autoincrement: true
    category_id: integer
    post_id: integer
  relations:
    Post:
      class: Post
      type: one
      foreignType: many
      local: post_id
      foreign: id
      foreignAlias: PostCategories
    Category:
      class: Category
      type: one
      foreignType: many
      local: category_id
      foreign: id
      foreignAlias: PostCategories
      
    
      
Category:
  columns:
    id: 
      type: integer
      primary: true
      autoincrement: true
    name: string(255)
  relations:
    Posts:
      class: Post
      refClass: PostCategory
      type: many
      foreignType: many
      local: category_id
      foreign: post_id
      foreignAlias: Categories
  actAs:
    NestedSet:
      hasManyRoots: true
      rootColumnName: root_id
    Sluggable:
      unique: true
      fields: [name]
      canUpdate: true
    